apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: docsstonesoupio-ltcb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: docsstonesoupio-ltcb
    app.kubernetes.io/part-of: jocelyn-test-app
  name: docsstonesoupio-ltcb
  namespace: jsese-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: docsstonesoupio-ltcb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: docsstonesoupio-ltcb
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:jsese-tenant-docsstonesoupio-ltcb
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
