apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: docsstonesoupio-ltcb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: docsstonesoupio-ltcb
    app.kubernetes.io/part-of: jocelyn-test-app
  name: docsstonesoupio-ltcb
  namespace: jsese-tenant
spec:
  path: /
  port:
    targetPort: 3001
  to:
    kind: Service
    name: docsstonesoupio-ltcb
    weight: null
status: {}
